### ISSUE TITLE
请问有没有可以举报广告帖的api

### ISSUE THREAD

**Issue by NeXT1995** [libsgh/tieba-api#1]
大神您好，请问有没有举报垃圾广告的api，我想用于消除各个贴吧的广告帖子

**Comment by libsgh** [comment]
需要实现怎样的功能，举报广告是手动的功能，你是想程序判断一个贴吧的帖子是不是广告贴，然后自动举报？类似贴吧防御吗？机器识别不是百分百，会有准确率的问题。

**Comment by NeXT1995** [comment]
是啊，但是我看了一下贴吧的举报功能有几个步骤，其中一个是选择举报的类型，然后再提交的。如果是完整的举报功能，有接口可以调用吗？

**Comment by libsgh** [comment]
> 是啊，但是我看了一下贴吧的举报功能有几个步骤，其中一个是选择举报的类型，然后再提交的。如果是完整的举报功能，有接口可以调用吗？

抽空我抓包看看，这里核心不是举报api，而是如何判断广告贴，如果有需要的话近期加一下

**Comment by libsgh** [comment]
v0.0.8中已经添加举报帖子的api，请使用最新版
