### ISSUE TITLE
求问大佬，回复楼中楼的时候，参数的顺序

### ISSUE THREAD

**Issue by 275761919** [libsgh/tieba-api#10]
发现参数的顺序也很重要，毕竟顺序不同，最后求出来的md5也不同。

所以想问下参数顺序有什么讲究吗，我试着交换一下顺序的都不行，

我自己抓包的时候还有很多别的参数，但是在你的源码里是被省略的，这些有什么说法吗

主要是我想实现在楼中楼回复具体某个人的功能，试了很久百度服务器总是返回未知错误，错误代码：110001。

**Comment by 275761919** [comment]
应该是BDUSS在最前面，其他的升序排序，感谢大佬的思路

**Comment by onedrive-x** [comment]
> 应该是BDUSS在最前面，其他的升序排序，感谢大佬的思路

有些参数是不必要的，这个需要测试，哪些是必要参数。参数加密是按照参数key升序排列。具体你可以看下签到那块的代码。v1.0.9已经更新了回帖接口，具体你参考下代码吧。

**Comment by libsgh** [comment]
有些参数是不必要的，这个需要测试，哪些是必要参数。参数加密是按照参数key升序排列。具体你可以看下签到那块的代码。v1.0.9已经更新了回帖接口，具体你参考下代码吧。
