### ISSUE TITLE
扫码无法登录

### ISSUE THREAD

**Issue by cryboy007** [libsgh/tieba-api#13]
二维码无法被app识别

**Comment by libsgh** [comment]
请反馈一下你的app版本

**Comment by cryboy007** [comment]
IOS版本11.9.2,贴吧极速版也不行

**Comment by cryboy007** [comment]
IOS版本11.9.2,IOS贴吧极速版也不行



study.hetao@foxmail.com
 
发件人： libsgh
发送时间： 2020-10-14 19:17
收件人： libsgh/tieba-api
抄送： cryboy007; Author
主题： Re: [libsgh/tieba-api] 扫码无法登录 (#13)
请反馈一下你的app版本
