### ISSUE TITLE
111

### ISSUE THREAD

**Issue by changliangxiang123** [libsgh/tieba-api#5]
测试的时候发现不能回帖，提示说 你的账号有风险，请更新到最新版本

**Comment by changliangxiang123** [comment]
> 测试的时候发现不能回帖，提示说 你的账号有风险，请更新到最新版本

已经解决了  要验证码

**Comment by libsgh** [comment]
之前的发帖代码可能需要手机验证码，新版的接口稳定了不少，建议用最新版。
